(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-save-default nil)
 '(auto-save-file-name-transforms (quote ((".*" "~/.emacs.d/autosave/" t))))
 '(auto-save-interval 20)
 '(auto-save-list-file-prefix "~/.emacs.d/autosave/")
 '(backup-by-copying t)
 '(backup-directory-alist (quote ((".*" . "~/.emacs.d/backup"))))
 '(bookmark-default-file "~/.emacs.d/etc/bookmarks")
 '(column-number-mode t)
 '(confirm-nonexistent-file-or-buffer t)
 '(current-language-environment "UTF-8")
 '(delete-old-versions t)
 '(delete-selection-mode t)
 '(dired-dwim-target t)
 '(dired-listing-switches "-alh")
 '(display-buffer-reuse-frames t)
 '(echo-keystrokes 0.1)
 '(eldoc-echo-area-use-multiline-p nil)
 '(eldoc-idle-delay 1.0)
 '(eshell-cmpl-autolist t)
 '(eshell-cmpl-compare-entry-function (quote string-lessp))
 '(eshell-error-if-no-glob t)
 '(eshell-plain-echo-behavior t)
 '(global-auto-revert-mode t)
 '(global-auto-revert-non-file-buffers t)
 '(hourglass-delay 2)
 '(ibuffer-expert t)
 '(icomplete-mode t)
 '(ido-confirm-unique-completion t)
 '(ido-create-new-buffer (quote always))
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(kept-new-versions 10)
 '(kept-old-versions 0)
 '(kill-whole-line t)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(read-file-name-completion-ignore-case t)
 '(recentf-max-menu-items 30)
 '(recentf-max-saved-items 300)
 '(recentf-save-file "~/.emacs.d/etc/recentf")
 '(savehist-file "~/.emacs.d/etc/history")
 '(savehist-mode t nil (savehist))
 '(scroll-bar-mode nil)
 '(show-paren-mode t)
 '(show-paren-style (quote mixed))
 '(tags-case-fold-search t)
 '(tool-bar-mode nil)
 '(use-dialog-box nil)
 '(use-file-dialog nil)
 '(vc-make-backup-files t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 )
